### ISSUE TITLE
Final Presentation 

### ISSUE THREAD

**Issue by Hussein-Ben** [GSoft-Goldsmiths/iLost-main#119]
upload slides by 4pm Friday 9th March

presentations start from 12 march to 19 march (over 2 weeks)

- 10 minutes presentation

- Question & Answer session

**GOAL:**
Give a brief overview of your entire project;

**- your motivation**

**- aims/objectives**

**- design**

**- development process**

**- outcomes to date**

**- testing and evaluation**

What we will be marked on:

- How clearly you describe the purpose and functioning of your syste

- Your account of the software development process

- Technical testing and user evaluation of the software in terms of the original requirements

- The quality of the presentation and how you handle any questions

**Comment by linuk** [comment]
Slides:

## 1. Motivation

* What makes we start this project?

## 2. aims/objectives

* As title

## 3. design

* User interface design
  * Android UI
  * iOS UI
* User journey design

## 4. development process

* Backlogs
* User stories
* Github work flow
* Agile development

## 5. outcomes to date

* iOS app
* Android app
* Tracker

## 6. testing and evaluation: 

* Mobile app testing (iOS/Android)
  * Mythology 
  * Evaluation
* Tracker testing
  * Mythology 
  * Evaluation

## 7. Tasks divided

* Who is account for what task

**Comment by Hussein-Ben** [comment]
I'm going to do Design (part 3), I already did design and implementation chapter in the report.

**Comment by linuk** [comment]
I'll integrate all the slides, I will start to make it from tomorrow. Will record it here if any part of it has been done. Let me know if anyone of you are interested in other parts, because there's only one week left and we don't have too much time.
@Hussein-Ben You can just upload the *texts* and *images* in each of part 3 slide, then I will integrate them with other parts. No need to worry about the layout of typography, I will handle it.

**Comment by Hussein-Ben** [comment]
uploaded script for Design part. Just need some good screenshots of the iOS/Android app in the slide

**Comment by mfakr001** [comment]
Where do we have to present

**Comment by mfakr001** [comment]
Is it gonna be in the lecture hall?

**Comment by linuk** [comment]
@Hussein-Ben 
About the mobile app demo in the design part, I think it's better to show it in **part 5: outcomes to date**. And In the design section we could just show the _UI design_ of both apps, what do you think ?

**Comment by linuk** [comment]
Most of the slides are finished apart from the part 5, 6 and 7.

@Hussein-Ben you can read the PDF file to see if the slides fit your need and would love to do any modification. Thanks!

**Comment by Hussein-Ben** [comment]
yes, the slides are perfect, we just need to talk through the presentation.

**Comment by Hussein-Ben** [comment]
I think your right with the suggestion, ill change my script but i don't know much about the UI design. we can show the app screenshots in outcomes

**Comment by mfakr001** [comment]
I could do 5 if no one has done so already. Also how can I see the where all the slides are?

**Comment by linuk** [comment]
I have finished all the slides, let me know if you want to add anything before tomorrow 4 pm. Link is on Slack.

Most of the works in part 4 to 6 are completed by myself, so I will do the presentation of them. Part 3 will be presented by @Hussein-Ben , let me know if you are interested in do the first 2 parts as well.
